### ISSUE TITLE
ExtensionLoader contains 1 abstract method and must therefore be declared abstract or implement the remaining methods 

### ISSUE THREAD

**Issue by Jade-GG** [indykoning/grumphp-duster#1]
`Fatal error: Class Indykoning\GrumPHPDuster\ExtensionLoader contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (GrumPHP\Extension\ExtensionInterface::imports) in [...]/vendor/indykoning/grumphp-duster/src/ExtensionLoader.php on line 11`

Possibly a PHP8.2 issue?

**Comment by indykoning** [comment]
This was an incompatibility between Grumphp V2 and the changes needed for the extensions for that release https://github.com/phpro/grumphp/commit/ec0cc3ad0f8414745c2c241331f4ab4fa0c9433d

This has been fixed in the latest release 🚀 
https://github.com/indykoning/grumphp-duster/releases/tag/2.0.0
